### ISSUE TITLE
001_LOC

### ISSUE THREAD

**Issue by sandeepny441** [mrachana47/pandas_Practise#1]
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

-- Create a dictionary with three keys, 'A', 'B', and 'C', and lists of 10 numbers as values
data = {'A': list(range(10)),
        'B': list(range(10, 20)),
        'C': list(range(20, 30))}

df1 = pd.DataFrame(data)

1. What value is in column 'C' for the row with index 2?
2. Select all columns where the values in column 'A' are less than 3.
3. Retrieve rows where the values in column 'C' are greater than 21.
4. How would you modify the value in column 'B' for row with index 3 to be 50?
5. Select rows where values in column 'A' are even.
6. Change the value in column 'C' to 100 where the value in column 'B' is greater than 15.
7. How can you set the value in column 'B' to 200 where the value in column 'A' is less than 2?
8. Retrieve values in column 'A' where column 'C' equals 100.
9. Set all rows with values in column 'B' less than 15 to -1.
10. Fetch rows where the values in column 'A' are either 2 or 3.
11. How would you change the values in column 'C' to 0 for rows where the values in column 'A' are even?
12. Retrieve rows where both column 'A' and column 'B' have values less than 0.
13. How would you filter rows where the values in column 'A' are either 1 or 4 using the isin method?
14. How would you use the apply method to categorize values in column 'A' based on a function, say categorizing them as 'even' or 'odd'?

**Comment by mrachana47** [comment]
Done with the tasks
